
const defaults={offers:['מיתוג','בידול','AI','בניית קהילה','שיווק','מכירות','תמחור','ניהול מוצר','כתיבה','עיצוב','הנחיית קבוצות','גיוס כספים'],needs:['פידבק על רעיון','דיוק הצעת ערך','שימוש ב-AI','תמחור','חיבור לשותפים','שיווק אורגני','בניית קהילה בתשלום','תמיכה טכנולוגית','מנטורינג קצר','השראה'],availability:['בוקר','צהריים','אחר הצהריים','ערב','ראשון','שני','שלישי','רביעי','חמישי']};
let state=JSON.parse(localStorage.getItem('sparkcoBraindatesV2')||'null')||{communityName:'קהילת Sparkco',taxonomy:defaults,me:{name:'',title:'',bio:'',offers:[],needs:[],availability:[],meetingTopic:''},people:[],invites:[]};
let selectedInvitePerson=null;const $=id=>document.getElementById(id);
function save(){localStorage.setItem('sparkcoBraindatesV2',JSON.stringify(state))}
function initials(name){return(name||'?').split(' ').filter(Boolean).slice(0,2).map(x=>x[0]).join('')||'?'}
function unique(arr){return[...new Set(arr.filter(Boolean))]}
function toggle(arr,val){const i=arr.indexOf(val);i>=0?arr.splice(i,1):arr.push(val)}
function chip(label,selected,onClick){const b=document.createElement('button');b.type='button';b.className='chip'+(selected?' selected':'');b.textContent=label;b.onclick=onClick;return b}
function renderChips(){[['offersChips','offers'],['needsChips','needs'],['availabilityChips','availability']].forEach(([el,key])=>{$(el).innerHTML='';state.taxonomy[key].forEach(t=>$(el).appendChild(chip(t,state.me[key].includes(t),()=>{toggle(state.me[key],t);render()})))})}
function syncForm(){['name','title','bio','meetingTopic'].forEach(k=>{if($(k))$(k).value=state.me[k]||''});$('communityName').value=state.communityName;$('adminOffers').value=state.taxonomy.offers.join(', ');$('adminNeeds').value=state.taxonomy.needs.join(', ')}
function updatePreview(){$('previewName').textContent=state.me.name||'השם שלך';$('previewTitle').textContent=state.me.title||'התפקיד שלך';$('previewBio').textContent=state.me.bio||'כאן יופיע המשפט שלך כפי שיועתק לפרופיל Sparkco.';$('avatarInitials').textContent=initials(state.me.name)}
function profileAsPerson(){return{...state.me,id:'me'}}
function calcMatches(){const me=state.me;return state.people.map(p=>{const offerNeed=p.offers.filter(x=>me.needs.includes(x));const needOffer=me.offers.filter(x=>p.needs.includes(x));const shared=unique(p.offers.concat(p.needs).filter(x=>me.offers.concat(me.needs).includes(x)));const avail=p.availability.filter(x=>me.availability.includes(x));let score=Math.min(98,34+offerNeed.length*18+needOffer.length*16+shared.length*5+avail.length*4);if(!me.name&&!me.bio)score=Math.max(58,score-16);const reasons=[];if(offerNeed.length)reasons.push(`${p.name} מביא/ה ${offerNeed.slice(0,3).join(', ')} — בדיוק משהו שסימנת שאת/ה מחפש/ת.`);if(needOffer.length)reasons.push(`יש לך יכולת לעזור ל-${p.name} ב-${needOffer.slice(0,3).join(', ')}.`);if(shared.length)reasons.push(`יש לכם שפה משותפת סביב ${shared.slice(0,3).join(', ')}.`);if(avail.length)reasons.push(`יש חפיפה בזמינות: ${avail.slice(0,3).join(', ')}.`);let matchType=offerNeed.length&&needOffer.length?'התאמה הדדית':offerNeed.length?'אפשר ללמוד ממנו/ה':needOffer.length?'אפשר לעזור לו/ה':'שיחה קהילתית מעניינת';return{...p,score,matchType,reasons:reasons.length?reasons:['יש כאן פוטנציאל לשיחת היכרות קהילתית קצרה.']}}).sort((a,b)=>b.score-a.score)}
function renderMatches(){const list=$('matchList');list.innerHTML='';const matches=calcMatches();if(!matches.length){list.innerHTML='<div class="empty">עדיין אין מספיק פרופילים בקהילה. לחצו על “טעינת דמו” כדי לראות את החוויה.</div>';return}matches.forEach(p=>{const c=document.createElement('div');c.className='card match-card';c.innerHTML=`<div class="score">${p.score}%</div><div><p class="eyebrow">${p.matchType}</p><h3>${p.name}</h3><p class="meta">${p.title}<br>${p.bio}</p><div class="tags">${unique([...p.offers,...p.needs]).slice(0,7).map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="match-explain"><strong>למה כדאי להיפגש?</strong><br>${p.reasons.join('<br>')}</div></div><div class="stack"><button class="primary invite-btn">הזמן/י לפגישה</button><button class="ghost save-btn">שמור לאחר כך</button></div>`;c.querySelector('.invite-btn').onclick=()=>openInvite(p);c.querySelector('.save-btn').onclick=()=>alert('בגרסה הבאה זה יישמר לרשימת “מעניין אותי”.');list.appendChild(c)})}
function renderPeople(){const grid=$('peopleGrid');grid.innerHTML='';const people=[profileAsPerson(),...state.people].filter(p=>p.name||p.bio||p.offers.length||p.needs.length);if(!people.length){grid.innerHTML='<div class="empty">מפת האנשים תתמלא אחרי שחברי הקהילה ימלאו פרופיל.</div>';return}people.forEach(p=>{const c=document.createElement('div');c.className='card person-card';c.innerHTML=`<div class="person-top"><div class="mini-avatar">${initials(p.name)}</div><div><h3>${p.name||'ללא שם'}</h3><p class="meta">${p.title||''}</p></div></div><p class="meta">${p.bio||''}</p><div class="tags">${(p.offers||[]).map(t=>`<span class="tag">נותן/ת: ${t}</span>`).join('')}${(p.needs||[]).map(t=>`<span class="tag">מבקש/ת: ${t}</span>`).join('')}</div>`;grid.appendChild(c)})}
function renderInvites(){const box=$('invitesList');box.innerHTML='';if(!state.invites.length){box.innerHTML='<div class="empty">עדיין לא נשלחו הזמנות. מתוך מסך ההתאמות אפשר לשלוח הזמנה עם מועדים מוצעים.</div>';return}state.invites.forEach((inv,idx)=>{const c=document.createElement('div');c.className='card invite-card';const status=inv.status||'pending';const label=status==='accepted'?'אושרה':status==='declined'?'נדחתה':'ממתינה';c.innerHTML=`<p class="eyebrow">Braindate Invite</p><h3>${inv.to}</h3><span class="status ${status}">${label}</span><p class="meta">${inv.message}</p><div class="tags">${inv.times.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="invite-actions"><button class="secondary accept-btn">סימון כאושרה</button><button class="ghost decline-btn">סימון כנדחתה</button></div>`;c.querySelector('.accept-btn').onclick=()=>{state.invites[idx].status='accepted';render()};c.querySelector('.decline-btn').onclick=()=>{state.invites[idx].status='declined';render()};box.appendChild(c)})}
function renderInsights(){const all=[profileAsPerson(),...state.people].filter(p=>p.name||p.bio||p.offers.length||p.needs.length);const count=key=>all.flatMap(p=>p[key]||[]).reduce((a,t)=>(a[t]=(a[t]||0)+1,a),{});const needs=count('needs'),offers=count('offers');const topNeeds=Object.entries(needs).sort((a,b)=>b[1]-a[1]).slice(0,5);const gaps=Object.keys(needs).filter(n=>!offers[n]).slice(0,5);const possibleGroups=topNeeds.filter(([k,v])=>v>=2).map(([k])=>k);$('adminInsights').innerHTML=`<div class="insight"><strong>${all.length}</strong> פרופילים במאגר הנוכחי</div><div class="insight"><strong>בקשות מובילות:</strong><br>${topNeeds.map(([k,v])=>`${k} (${v})`).join(' · ')||'אין עדיין נתונים'}</div><div class="insight"><strong>פערים אפשריים:</strong><br>${gaps.join(' · ')||'לא זוהו פערים משמעותיים'}</div><div class="insight"><strong>חדרים קבוצתיים שכדאי לשקול:</strong><br>${possibleGroups.join(' · ')||'עדיין אין מספיק ביקוש חוזר'}</div>`}
function render(){syncForm();renderChips();updatePreview();renderMatches();renderPeople();renderInvites();renderInsights();save()}
function closeInvite(){const dlg=$('inviteDialog');if(dlg&&dlg.open)dlg.close()}
function openInvite(p){selectedInvitePerson=p;$('inviteTitle').textContent=`הזמנה ל-${p.name}`;$('inviteReason').innerHTML=`<strong>${p.score}% התאמה · ${p.matchType}</strong><br>${p.reasons.join('<br>')}`;$('inviteMessage').value=`היי ${p.name},\nראיתי שהמערכת הציעה בינינו חיבור רלוונטי.\n${p.reasons[0]}\nאשמח לשיחת Braindate קצרה של 25 דקות.`;$('inviteTimes').value='ראשון 10:00\nשלישי 17:30\nחמישי 20:00';const dlg=$('inviteDialog');dlg.showModal?dlg.showModal():dlg.setAttribute('open','open')}
function suggestBioText(){const existing=(state.me.bio||'').trim();if(existing&&existing.length<=120)return existing;if(existing)return existing.slice(0,117).trim()+'...';const offer=state.me.offers.slice(0,2).join(' ו');const need=state.me.needs.slice(0,2).join(' ו');return`מביא/ה ${offer||'ידע וניסיון'}, ומחפש/ת חיבורים סביב ${need||'למידה ושיתופי פעולה'}.`}
function seed(){state.people=[{id:'1',name:'גליה רוזן',title:'מומחית Design Thinking ומיתוג',bio:'עוזרת לעסקים לדייק בידול, שפה והצעת ערך.',offers:['מיתוג','בידול','הנחיית קבוצות'],needs:['בניית קהילה בתשלום','שימוש ב-AI'],availability:['בוקר','שלישי','חמישי']},{id:'2',name:'מירב כהן',title:'יועצת עסקית',bio:'מביאה ניסיון בתוכניות עסקיות, תמחור, מכירות ותשתיות צמיחה.',offers:['תמחור','מכירות','שיווק'],needs:['בניית קהילה','AI'],availability:['צהריים','ראשון','רביעי']},{id:'3',name:'עדי ברק',title:'מנהלת קהילות',bio:'בונה מרחבי למידה וקהילות סביב ידע, אמון ותרגול.',offers:['בניית קהילה','הנחיית קבוצות','כתיבה'],needs:['גיוס כספים','דיוק הצעת ערך'],availability:['ערב','שני','רביעי']},{id:'4',name:'נועה לוי',title:'יוצרת תוכן ו-AI',bio:'עוזרת לאנשים לבנות תהליכי עבודה פשוטים עם כלי AI.',offers:['AI','כתיבה','עיצוב'],needs:['מכירות','מיתוג'],availability:['אחר הצהריים','שלישי','חמישי']},{id:'5',name:'רוני אברהם',title:'יזמת בתחילת הדרך',bio:'מחפשת לדייק הצעת ערך ולפגוש אנשים שחושבים קהילה.',offers:['כתיבה','שיווק'],needs:['דיוק הצעת ערך','מיתוג','תמחור'],availability:['בוקר','ראשון','שלישי']}];if(!state.me.name){state.me={name:'ניב הורוביץ',title:'בונה מרחבי קהילה ולמידה ב-Sparkco',bio:'מביא חשיבה קהילתית, פדגוגית ומוצרית, ומחפש חיבורים סביב קהילות ידע ו-AI.',offers:['בניית קהילה','AI','הנחיית קבוצות'],needs:['מיתוג','תמחור','חיבור לשותפים'],availability:['בוקר','צהריים','שלישי','רביעי'],meetingTopic:'אשמח לפגוש אנשים שרוצים להפוך ידע קיים בקהילה למפגשים בעלי ערך.'}}render()}
document.querySelectorAll('.nav-item').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav-item').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(btn.dataset.view+'View').classList.add('active');$('viewTitle').textContent=btn.textContent});
document.querySelectorAll('[data-go]').forEach(btn=>btn.onclick=()=>document.querySelector(`[data-view="${btn.dataset.go}"]`).click());
['name','title','bio','meetingTopic'].forEach(k=>$(k).addEventListener('input',e=>{state.me[k]=e.target.value;render()}));
$('suggestBio').onclick=()=>{$('bioSuggestion').textContent=suggestBioText();$('bioSuggestionBox').classList.remove('hidden')};
$('useSuggestion').onclick=()=>{state.me.bio=$('bioSuggestion').textContent;$('bioSuggestionBox').classList.add('hidden');render()};
$('dismissSuggestion').onclick=()=>$('bioSuggestionBox').classList.add('hidden');
$('copyBio').onclick=async()=>{try{await navigator.clipboard.writeText(state.me.bio||'');$('copyStatus').textContent='המשפט הועתק. אפשר להדביק בפרופיל Sparkco.'}catch(e){$('copyStatus').textContent='אפשר לסמן ולהעתיק ידנית מתוך תיבת הביו.'}};
$('seedDemo').onclick=seed;$('addDemoPerson').onclick=seed;$('refreshMatches').onclick=renderMatches;$('saveAll').onclick=()=>{save();alert('נשמר מקומית בדפדפן')};
$('exportData').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sparkco-braindates-data.json';a.click();URL.revokeObjectURL(a.href)};
$('saveAdmin').onclick=()=>{state.communityName=$('communityName').value;state.taxonomy.offers=$('adminOffers').value.split(',').map(x=>x.trim()).filter(Boolean);state.taxonomy.needs=$('adminNeeds').value.split(',').map(x=>x.trim()).filter(Boolean);render()};
$('sendInvite').onclick=()=>{if(!selectedInvitePerson)return;state.invites.unshift({to:selectedInvitePerson.name,message:$('inviteMessage').value,times:$('inviteTimes').value.split('\n').map(x=>x.trim()).filter(Boolean),status:'pending',createdAt:new Date().toISOString()});closeInvite();document.querySelector('[data-view="invites"]').click();render()};
$('cancelInvite').onclick=closeInvite;$('closeInviteX').onclick=closeInvite;$('inviteDialog').addEventListener('click',e=>{if(e.target===$('inviteDialog'))closeInvite()});
render();
