
const defaults = {
  offers:['מיתוג','בידול','AI','בניית קהילה','שיווק','מכירות','תמחור','ניהול מוצר','כתיבה','עיצוב','הנחיית קבוצות','גיוס כספים','חינוך','ליווי אישי'],
  needs:['פידבק על רעיון','דיוק הצעת ערך','שימוש ב-AI','תמחור','חיבור לשותפים','שיווק אורגני','בניית קהילה בתשלום','תמיכה טכנולוגית','מנטורינג קצר','השראה','לקוחות ראשונים'],
  availability:['בוקר','צהריים','אחר הצהריים','ערב','ראשון','שני','שלישי','רביעי','חמישי'],
  meetingStyles:['שיחת היכרות קצרה','פידבק ממוקד','חשיבה משותפת','מנטורינג קצר','שיחת עומק','קבוצה קטנה'],
  openness:['פתוח/ה לפניות','רק התאמות מדויקות','פנוי/ה לשיחה אחת השבוע','מעדיף/ה קבוצה קטנה','כרגע רק מתבונן/ת']
};
let state = JSON.parse(localStorage.getItem('sparkcoBraindatesV3') || 'null') || {
  communityName:'קהילת Sparkco',
  taxonomy: defaults,
  me:{name:'',title:'',bio:'',photo:'',offers:[],needs:[],availability:[],meetingStyles:[],openness:[],currentFocus:'',braindateOffer:'',lookingToMeet:'',link:'',location:''},
  people:[],
  invites:[],
  activeReport:'overview'
};
let selectedInvitePerson = null;
const $ = id => document.getElementById(id);
function save(){ localStorage.setItem('sparkcoBraindatesV3', JSON.stringify(state)); }
function unique(arr){ return [...new Set((arr || []).filter(Boolean))]; }
function initials(name){ return (name || '?').split(' ').filter(Boolean).slice(0,2).map(x=>x[0]).join('') || '?'; }
function toggle(arr,val){ const i=arr.indexOf(val); i>=0 ? arr.splice(i,1) : arr.push(val); }
function profileAsPerson(){ return {...state.me, id:'me'}; }
function chip(label, selected, onClick){ const b=document.createElement('button'); b.type='button'; b.className='chip'+(selected?' selected':''); b.textContent=label; b.onclick=onClick; return b; }
function renderChipSet(el,taxonomyKey,userKey){ const target=$(el); target.innerHTML=''; state.taxonomy[taxonomyKey].forEach(t=>target.appendChild(chip(t,(state.me[userKey]||[]).includes(t),()=>{ if(!state.me[userKey]) state.me[userKey]=[]; toggle(state.me[userKey],t); render(); }))); }
function renderChips(){ renderChipSet('offersChips','offers','offers'); renderChipSet('needsChips','needs','needs'); renderChipSet('availabilityChips','availability','availability'); renderChipSet('meetingStyleChips','meetingStyles','meetingStyles'); renderChipSet('opennessChips','openness','openness'); }
function syncForm(){ ['name','title','bio','currentFocus','braindateOffer','lookingToMeet','link','location'].forEach(k=>{ if($(k)) $(k).value=state.me[k]||''; }); $('communityName').value=state.communityName; $('adminOffers').value=state.taxonomy.offers.join(', '); $('adminNeeds').value=state.taxonomy.needs.join(', '); }
function profileCompletion(){ const fields=[!!state.me.name,!!state.me.title,!!state.me.bio,!!state.me.photo,state.me.offers.length>0,state.me.needs.length>0,!!state.me.currentFocus,!!state.me.braindateOffer,!!state.me.lookingToMeet,state.me.availability.length>0,state.me.meetingStyles.length>0,state.me.openness.length>0]; return Math.round(fields.filter(Boolean).length/fields.length*100); }
function setPhoto(el, photo, fallback){ const node=$(el); if(photo){ node.style.backgroundImage=`url(${photo})`; node.textContent=''; } else { node.style.backgroundImage=''; node.textContent=fallback; } }
function updatePreview(){ $('previewName').textContent=state.me.name||'השם שלך'; $('previewTitle').textContent=state.me.title||'התפקיד שלך'; $('previewBio').textContent=state.me.bio||'המשפט האישי שלך יופיע כאן.'; $('completionScore').textContent=profileCompletion()+'%'; const fallback=initials(state.me.name); setPhoto('photoPreview',state.me.photo,fallback); setPhoto('publicPhoto',state.me.photo,fallback); const tags=unique([...state.me.offers,...state.me.needs,...state.me.meetingStyles]).slice(0,8); $('previewTags').innerHTML=tags.map(t=>`<span class="tag">${t}</span>`).join(''); }
function calcMatches(){ const me=state.me; return state.people.map(p=>{ const offerNeed=(p.offers||[]).filter(x=>me.needs.includes(x)); const needOffer=me.offers.filter(x=>(p.needs||[]).includes(x)); const shared=unique([...(p.offers||[]),...(p.needs||[])].filter(x=>[...me.offers,...me.needs].includes(x))); const style=(p.meetingStyles||[]).filter(x=>me.meetingStyles.includes(x)); const avail=(p.availability||[]).filter(x=>me.availability.includes(x)); const opennessBonus=(me.openness.includes('פתוח/ה לפניות')||(p.openness||[]).includes('פתוח/ה לפניות'))?6:0; let score=Math.min(98,28+offerNeed.length*18+needOffer.length*16+shared.length*5+style.length*5+avail.length*4+opennessBonus); if(!me.name&&!me.bio) score=Math.max(45,score-18); const reasons=[]; if(offerNeed.length) reasons.push(`${p.name} מביא/ה ${offerNeed.slice(0,3).join(', ')} — בדיוק משהו שסימנת שאת/ה מחפש/ת.`); if(needOffer.length) reasons.push(`יש לך יכולת לעזור ל-${p.name} ב-${needOffer.slice(0,3).join(', ')}.`); if(shared.length) reasons.push(`יש לכם שפה משותפת סביב ${shared.slice(0,3).join(', ')}.`); if(style.length) reasons.push(`שניכם פתוחים לסוג מפגש דומה: ${style.slice(0,2).join(', ')}.`); if(avail.length) reasons.push(`יש חפיפה בזמינות: ${avail.slice(0,3).join(', ')}.`); const matchType=offerNeed.length&&needOffer.length?'התאמה הדדית':offerNeed.length?'אפשר ללמוד ממנו/ה':needOffer.length?'אפשר לעזור לו/ה':'שיחה קהילתית מעניינת'; return {...p,score,matchType,reasons:reasons.length?reasons:['יש כאן פוטנציאל לשיחת היכרות קהילתית קצרה.']}; }).sort((a,b)=>b.score-a.score); }
function renderMatches(){ const list=$('matchList'); list.innerHTML=''; const matches=calcMatches(); if(!matches.length){ list.innerHTML='<div class="empty">עדיין אין מספיק פרופילים בקהילה. לחצו על “טעינת דמו” כדי לראות את החוויה.</div>'; return; } matches.forEach(p=>{ const c=document.createElement('div'); c.className='card match-card'; const photoStyle=p.photo?`style="background-image:url(${p.photo})"`:''; c.innerHTML=`<div class="score">${p.score}%</div><div><div class="person-top"><div class="mini-avatar" ${photoStyle}>${p.photo?'':initials(p.name)}</div><div><p class="eyebrow">${p.matchType}</p><h3>${p.name}</h3><p class="meta">${p.title||''}</p></div></div><p class="meta">${p.bio||''}</p><div class="tags">${unique([...(p.offers||[]),...(p.needs||[]),...(p.meetingStyles||[])]).slice(0,7).map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="match-explain"><strong>למה כדאי להיפגש?</strong><br>${p.reasons.join('<br>')}</div></div><div class="stack"><button class="primary invite-btn">הזמן/י לפגישה</button><button class="ghost save-btn">שמור לאחר כך</button></div>`; c.querySelector('.invite-btn').onclick=()=>openInvite(p); c.querySelector('.save-btn').onclick=()=>alert('בגרסה הבאה זה יישמר לרשימת “מעניין אותי”.'); list.appendChild(c); }); }
function renderPeople(){ const grid=$('peopleGrid'); grid.innerHTML=''; const people=[profileAsPerson(),...state.people].filter(p=>p.name||p.bio||(p.offers||[]).length||(p.needs||[]).length); if(!people.length){ grid.innerHTML='<div class="empty">מפת האנשים תתמלא אחרי שחברי הקהילה ימלאו פרופיל.</div>'; return; } people.forEach(p=>{ const c=document.createElement('div'); c.className='card person-card'; const photoStyle=p.photo?`style="background-image:url(${p.photo})"`:''; c.innerHTML=`<div class="person-top"><div class="mini-avatar" ${photoStyle}>${p.photo?'':initials(p.name)}</div><div><h3>${p.name||'ללא שם'}</h3><p class="meta">${p.title||''}</p></div></div><p class="meta">${p.bio||''}</p>${p.currentFocus?`<div class="match-explain"><strong>מעניין אותי עכשיו:</strong><br>${p.currentFocus}</div>`:''}${p.braindateOffer?`<p class="meta"><strong>מציע/ה Braindate:</strong> ${p.braindateOffer}</p>`:''}<div class="tags">${(p.offers||[]).slice(0,5).map(t=>`<span class="tag">נותן/ת: ${t}</span>`).join('')}${(p.needs||[]).slice(0,5).map(t=>`<span class="tag">מבקש/ת: ${t}</span>`).join('')}</div>`; grid.appendChild(c); }); }
function allProfiles(){ return [profileAsPerson(),...state.people].filter(p=>p.name||p.bio||(p.offers||[]).length||(p.needs||[]).length); }
function countBy(key){ return allProfiles().flatMap(p=>p[key]||[]).reduce((a,t)=>(a[t]=(a[t]||0)+1,a),{}); }
function sortedCounts(obj){ return Object.entries(obj).sort((a,b)=>b[1]-a[1]); }
function renderRooms(){ const grid=$('roomsGrid'); const needs=sortedCounts(countBy('needs')); const offers=countBy('offers'); const rooms=needs.slice(0,6).map(([need,count])=>({title:`חדר Braindate: ${need}`,count,helpers:offers[need]||0,reason:offers[need]?`יש ${count} מבקשים/ות ו-${offers[need]} שיכולים/ות לעזור.`:`יש ביקוש, אבל לא זוהו עדיין מספיק אנשים שמציעים את זה.`})); if(!rooms.length){ grid.innerHTML='<div class="empty">כשהקהילה תמלא פרופילים, נציע כאן חדרים לפתיחה בספארקו.</div>'; return; } grid.innerHTML=rooms.map(r=>`<div class="card room-card"><p class="eyebrow">Suggested Sparkco Room</p><h3>${r.title}</h3><div class="room-count">${r.count}</div><p class="meta">${r.reason}</p><button class="ghost">פתחו חדר כזה השבוע</button></div>`).join(''); }
function renderInvites(){ const box=$('invitesList'); box.innerHTML=''; if(!state.invites.length){ box.innerHTML='<div class="empty">עדיין לא נשלחו הזמנות. מתוך מסך ההתאמות אפשר לשלוח הזמנה עם מועדים מוצעים.</div>'; return; } state.invites.forEach((inv,idx)=>{ const c=document.createElement('div'); c.className='card invite-card'; const status=inv.status||'pending'; const statusLabel=status==='accepted'?'אושרה':status==='declined'?'נדחתה':'ממתינה'; c.innerHTML=`<p class="eyebrow">Braindate Invite</p><h3>${inv.to}</h3><span class="status ${status}">${statusLabel}</span><p class="meta">${inv.message}</p><div class="tags">${inv.times.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="invite-actions"><button class="secondary accept-btn">סימון כאושרה</button><button class="ghost decline-btn">סימון כנדחתה</button></div>`; c.querySelector('.accept-btn').onclick=()=>{state.invites[idx].status='accepted'; render();}; c.querySelector('.decline-btn').onclick=()=>{state.invites[idx].status='declined'; render();}; box.appendChild(c); }); }
function kpis(){ const profiles=allProfiles(); return [['פרופילים',profiles.length],['פתוחים לפניות',profiles.filter(p=>(p.openness||[]).includes('פתוח/ה לפניות')).length],['הזמנות',state.invites.length],['מפגשים אושרו',state.invites.filter(i=>i.status==='accepted').length]]; }
function reportRows(title,entries,max){ if(!entries.length) return `<div class="empty">אין עדיין מספיק נתונים עבור ${title}</div>`; return `<div class="report-list">${entries.map(([k,v])=>`<div class="report-row"><div><strong>${k}</strong><div class="bar"><span style="width:${Math.max(7,Math.round(v/max*100))}%"></span></div></div><strong>${v}</strong></div>`).join('')}</div>`; }
function renderAdmin(){ $('kpiGrid').innerHTML=kpis().map(([label,value])=>`<div class="kpi"><strong>${value}</strong><span>${label}</span></div>`).join(''); const needs=sortedCounts(countBy('needs')); const offers=sortedCounts(countBy('offers')); const needMap=countBy('needs'); const offerMap=countBy('offers'); const gaps=Object.entries(needMap).map(([k,v])=>[k,v-(offerMap[k]||0)]).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]); const people=allProfiles().map(p=>[p.name||'ללא שם',(p.offers||[]).length*2+(p.needs||[]).length+(p.braindateOffer?3:0)]).sort((a,b)=>b[1]-a[1]).slice(0,8); let html=''; if(state.activeReport==='overview') html=`<div class="insight"><strong>מה הקהילה צריכה עכשיו:</strong><br>${needs.slice(0,5).map(([k,v])=>`${k} (${v})`).join(' · ')||'אין עדיין נתונים'}</div><div class="insight"><strong>מה הקהילה יודעת לתת:</strong><br>${offers.slice(0,5).map(([k,v])=>`${k} (${v})`).join(' · ')||'אין עדיין נתונים'}</div><div class="insight"><strong>המלצה:</strong><br>כשיש 4+ אנשים סביב אותו צורך, כדאי לפתוח חדר Braindate קבוצתי בספארקו.</div>`; if(state.activeReport==='needs') html=reportRows('צרכים',needs.slice(0,12),needs[0]?.[1]||1); if(state.activeReport==='offers') html=reportRows('יכולות',offers.slice(0,12),offers[0]?.[1]||1); if(state.activeReport==='gaps') html=reportRows('פערים',gaps.slice(0,12),gaps[0]?.[1]||1); if(state.activeReport==='people') html=reportRows('אנשים מרכזיים',people,people[0]?.[1]||1); $('adminReport').innerHTML=html; }
function render(){ syncForm(); renderChips(); updatePreview(); renderMatches(); renderPeople(); renderRooms(); renderInvites(); renderAdmin(); save(); }
function closeInvite(){ const dlg=$('inviteDialog'); if(dlg&&dlg.open) dlg.close(); }
function openInvite(p){ selectedInvitePerson=p; $('inviteTitle').textContent=`הזמנה ל-${p.name}`; $('inviteReason').innerHTML=`<strong>${p.score}% התאמה · ${p.matchType}</strong><br>${p.reasons.join('<br>')}`; $('inviteMessage').value=`היי ${p.name},\nראיתי שהמערכת הציעה בינינו חיבור רלוונטי.\n${p.reasons[0]}\nאשמח לשיחת Braindate קצרה של 25 דקות.`; $('inviteTimes').value='ראשון 10:00\nשלישי 17:30\nחמישי 20:00'; const dlg=$('inviteDialog'); dlg.showModal?dlg.showModal():dlg.setAttribute('open','open'); }
function suggestBioText(){ const existing=(state.me.bio||'').trim(); if(existing&&existing.length<=120) return existing; if(existing) return existing.slice(0,117).trim()+'...'; const offer=state.me.offers.slice(0,2).join(' ו'); const need=state.me.needs.slice(0,2).join(' ו'); return `מביא/ה ${offer||'ידע וניסיון'}, ומחפש/ת חיבורים סביב ${need||'למידה ושיתופי פעולה'}.`; }
function addCustomTag(inputId,taxonomyKey,userKey){ const value=$(inputId).value.trim(); if(!value) return; if(!state.taxonomy[taxonomyKey].includes(value)) state.taxonomy[taxonomyKey].push(value); if(!state.me[userKey].includes(value)) state.me[userKey].push(value); $(inputId).value=''; render(); }
function seed(){ state.people=[{id:'1',name:'גליה רוזן',title:'מומחית Design Thinking ומיתוג',bio:'עוזרת לעסקים לדייק בידול, שפה והצעת ערך.',photo:'',offers:['מיתוג','בידול','הנחיית קבוצות'],needs:['בניית קהילה בתשלום','שימוש ב-AI'],availability:['בוקר','שלישי','חמישי'],meetingStyles:['פידבק ממוקד','חשיבה משותפת'],openness:['פתוח/ה לפניות'],currentFocus:'איך להפוך קהילה עסקית למרחב של חברות מתמשכת.',braindateOffer:'פידבק על בידול ומסר שיווקי ב-25 דקות'},{id:'2',name:'מירב כהן',title:'יועצת עסקית',bio:'מביאה ניסיון בתוכניות עסקיות, תמחור, מכירות ותשתיות צמיחה.',photo:'',offers:['תמחור','מכירות','שיווק'],needs:['בניית קהילה','AI'],availability:['צהריים','ראשון','רביעי'],meetingStyles:['מנטורינג קצר','פידבק ממוקד'],openness:['רק התאמות מדויקות'],currentFocus:'מודלים עסקיים לקהילות קטנות.',braindateOffer:'דיוק תמחור והצעת ערך'},{id:'3',name:'עדי ברק',title:'מנהלת קהילות',bio:'בונה מרחבי למידה וקהילות סביב ידע, אמון ותרגול.',photo:'',offers:['בניית קהילה','הנחיית קבוצות','כתיבה'],needs:['גיוס כספים','דיוק הצעת ערך'],availability:['ערב','שני','רביעי'],meetingStyles:['שיחת עומק','קבוצה קטנה'],openness:['פתוח/ה לפניות'],currentFocus:'איך יוצרים השתתפות קבועה ולא רק אירועים.',braindateOffer:'חשיבה על מבנה קהילה שבועי'},{id:'4',name:'נועה לוי',title:'יוצרת תוכן ו-AI',bio:'עוזרת לאנשים לבנות תהליכי עבודה פשוטים עם כלי AI.',photo:'',offers:['AI','כתיבה','עיצוב'],needs:['מכירות','מיתוג'],availability:['אחר הצהריים','שלישי','חמישי'],meetingStyles:['שיחת היכרות קצרה','פידבק ממוקד'],openness:['פתוח/ה לפניות'],currentFocus:'כלי AI ליוצרי תוכן וקהילות.',braindateOffer:'היכרות מהירה עם כלי AI פרקטיים'},{id:'5',name:'רוני אברהם',title:'יזמת בתחילת הדרך',bio:'מחפשת לדייק הצעת ערך ולפגוש אנשים שחושבים קהילה.',photo:'',offers:['כתיבה','שיווק'],needs:['דיוק הצעת ערך','מיתוג','תמחור'],availability:['בוקר','ראשון','שלישי'],meetingStyles:['חשיבה משותפת','שיחת היכרות קצרה'],openness:['פנוי/ה לשיחה אחת השבוע'],currentFocus:'להבין איך להתחיל למכור בלי להרגיש מכירתית.',braindateOffer:'שיחה פתוחה על כתיבה אותנטית'}]; if(!state.me.name){ state.me={name:'ניב הורוביץ',title:'בונה מרחבי קהילה ולמידה ב-Sparkco',bio:'מביא חשיבה קהילתית, פדגוגית ומוצרית, ומחפש חיבורים סביב קהילות ידע ו-AI.',photo:'',offers:['בניית קהילה','AI','הנחיית קבוצות'],needs:['מיתוג','תמחור','חיבור לשותפים'],availability:['בוקר','צהריים','שלישי','רביעי'],meetingStyles:['חשיבה משותפת','שיחת עומק'],openness:['פתוח/ה לפניות'],currentFocus:'איך להפוך ידע, קשרים ונוכחות בקהילה למפגשים שמייצרים ערך אמיתי.',braindateOffer:'חשיבה של 25 דקות על מודל קהילה בתשלום',lookingToMeet:'מישהו/י שרוצה לבנות קהילה סביב ידע קיים',link:'',location:'אונליין'}; } render(); }
document.querySelectorAll('.nav-item').forEach(btn=>btn.onclick=()=>{ document.querySelectorAll('.nav-item').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); document.querySelectorAll('.view').forEach(v=>v.classList.remove('active')); $(btn.dataset.view+'View').classList.add('active'); $('viewTitle').textContent=btn.textContent; });
document.querySelectorAll('[data-go]').forEach(btn=>btn.onclick=()=>document.querySelector(`[data-view="${btn.dataset.go}"]`).click());
['name','title','bio','currentFocus','braindateOffer','lookingToMeet','link','location'].forEach(k=>$(k).addEventListener('input',e=>{ state.me[k]=e.target.value; render(); }));
$('photoInput').addEventListener('change',e=>{ const file=e.target.files[0]; if(!file) return; const reader=new FileReader(); reader.onload=()=>{ state.me.photo=reader.result; render(); }; reader.readAsDataURL(file); });
$('addOffer').onclick=()=>addCustomTag('customOffer','offers','offers'); $('addNeed').onclick=()=>addCustomTag('customNeed','needs','needs');
$('suggestBio').onclick=()=>{ $('bioSuggestion').textContent=suggestBioText(); $('bioSuggestionBox').classList.remove('hidden'); };
$('useSuggestion').onclick=()=>{ state.me.bio=$('bioSuggestion').textContent; $('bioSuggestionBox').classList.add('hidden'); render(); };
$('dismissSuggestion').onclick=()=>$('bioSuggestionBox').classList.add('hidden');
$('copyBio').onclick=async()=>{ try{ await navigator.clipboard.writeText(state.me.bio||''); $('copyStatus').textContent='המשפט הועתק. אפשר להדביק בפרופיל Sparkco.'; }catch(e){ $('copyStatus').textContent='אפשר לסמן ולהעתיק ידנית מתוך תיבת הביו.'; } };
$('seedDemo').onclick=seed; $('addDemoPerson').onclick=seed; $('refreshMatches').onclick=renderMatches; $('saveAll').onclick=()=>{ save(); alert('נשמר מקומית בדפדפן'); };
$('exportData').onclick=()=>{ const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='sparkco-braindates-data.json'; a.click(); URL.revokeObjectURL(a.href); };
$('saveAdmin').onclick=()=>{ state.communityName=$('communityName').value; state.taxonomy.offers=$('adminOffers').value.split(',').map(x=>x.trim()).filter(Boolean); state.taxonomy.needs=$('adminNeeds').value.split(',').map(x=>x.trim()).filter(Boolean); render(); };
document.querySelectorAll('.report-tab').forEach(btn=>btn.onclick=()=>{ document.querySelectorAll('.report-tab').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); state.activeReport=btn.dataset.report; render(); });
$('sendInvite').onclick=()=>{ if(!selectedInvitePerson) return; state.invites.unshift({to:selectedInvitePerson.name,message:$('inviteMessage').value,times:$('inviteTimes').value.split('\n').map(x=>x.trim()).filter(Boolean),status:'pending',createdAt:new Date().toISOString()}); closeInvite(); document.querySelector('[data-view="invites"]').click(); render(); };
$('cancelInvite').onclick=closeInvite; $('closeInviteX').onclick=closeInvite; $('inviteDialog').addEventListener('click',e=>{ if(e.target===$('inviteDialog')) closeInvite(); });
render();
